services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: 'fiapburger'
  rabbitmq:
    image: fiapburger/rabbitmq:3-management-delayed
    build:
      context: ./localstack
      dockerfile: ./Dockerfile.rabbitmq
    container_name: fiapburger-rabbitmq
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: 'fiapburger'
      RABBITMQ_DEFAULT_PASS: 'fiapburger'
    ports:
      - 5672:5672
      - 15672:15672