---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fiap-burger-orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fiap-burger-orders
  template:
    metadata:
      labels:
        app: fiap-burger-orders
    spec:
      terminationGracePeriodSeconds: 90
      automountServiceAccountToken: false
      containers:
        - name: fiap-burger-orders-app
          image: gm50x/fiap-burger-orders:latest
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: fiap-burger-orders
          env:
            - name: NODE_ENV
              value: "production"
            - name: APP_NAME
              value: "FiapBurgerOrder"
            - name: APP_DESCRIPTION
              value: "Orders Component for Fiap Burger"
            - name: APP_VERSION
              value: "1.0.0"
            - name: PORT
              value: "3000"
            - name: LOG_LEVEL
              value: "info"
            - name: LOG_FORMAT
              value: "pretty" # pretty | json
            - name: TRAFFIC_INSPECTION_HTTP
              value: "all" # inbound|outbound|all|none
            - name: TRAFFIC_INSPECTION_AMQP
              value: "all" # inbound|outbound|all|none
            - name: ROUTE_PREFIX
              value: "fiap-burger-orders"
          ports:
            - name: http
              containerPort: 3000
          resources:
            requests:
              cpu: 100m
              memory: "256Mi"
            limits:
              cpu: 450m
              memory: "512Mi"
          livenessProbe:
            initialDelaySeconds: 10
            failureThreshold: 3
            periodSeconds: 15
            httpGet:
              path: /fiap-burger-orders/healthz
              port: 3000
          readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 10
            httpGet:
              path: /fiap-burger-orders/healthz/self
              port: 3000
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fiap-burger-orders-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fiap-burger-orders
  minReplicas: 1
  maxReplicas: 10
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 30
      policies:
        - type: Pods
          value: 1
          periodSeconds: 30
    scaleUp:
      stabilizationWindowSeconds: 30
      policies:
        - type: Percent
          value: 100
          periodSeconds: 30
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 150
---
apiVersion: v1
kind: Service
metadata:
  name: fiap-burger-orders-lb-srv
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
spec:
  selector:
    app: fiap-burger-orders
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
